# -*- coding: utf-8 -*-
"""Project VSS video summery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAATIZJegy2Zl_kqmmte7fmTqUM6k90l
"""



""" **Source details and links**

 https://build.nvidia.com/nvidia/video-search-and-summarization/blueprintcard

 https://www.kaggle.com/datasets/klemenko/kitti-dataset?select=data_object_calib

https://www.kaggle.com/datasets/bratjay/ua-detrac-orig
"""

# Hardware and software configuration
import torch

if not torch.cuda.is_available():
    raise RuntimeError("No GPU — Runtime → Change runtime type → GPU → A100")

gpu_name = torch.cuda.get_device_name(0)
vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9

print(f"GPU  : {gpu_name}")
print(f"VRAM : {vram_gb:.1f} GB")
print(f"CUDA : {torch.version.cuda}")

if "A100" not in gpu_name:
    print("Not A100 — disconnect and reconnect to get A100")
else:
    print("A100 confirmed — ready to proceed")


#GPU SET UP and Info

!pip install -q \
  "transformers>=4.45.0" \
  accelerate \
  qwen-vl-utils \
  opencv-python-headless \
  Pillow \
  tqdm

import transformers, cv2
from PIL import Image
from qwen_vl_utils import process_vision_info

print(f"transformers : {transformers.__version__}")
print(f"OpenCV       : {cv2.__version__}")
print("qwen-vl-utils: OK")

import cv2
from google.colab import files

print("A file picker will appear below — select your video...")
uploaded   = files.upload()
VIDEO_PATH = list(uploaded.keys())[0]
print(f"Uploaded: {VIDEO_PATH}")

cap          = cv2.VideoCapture(VIDEO_PATH)
assert cap.isOpened(), f"Cannot open video: {VIDEO_PATH}"

fps          = cap.get(cv2.CAP_PROP_FPS)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
duration_s   = total_frames / fps
cap.release()

print(f"Duration : {duration_s:.1f}s  ({duration_s/60:.1f} min)")
print(f"FPS      : {fps:.2f}")
print(f"Frames   : {total_frames}")
print("Video is readable and ready")

import torch
from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info

VLM_ID = "Qwen/Qwen2-VL-7B-Instruct"
print(f"Loading {VLM_ID} into GPU memory...")
print("First run downloads ~15GB — this is normal\n")

vlm_processor = AutoProcessor.from_pretrained(VLM_ID)

vlm_model = Qwen2VLForConditionalGeneration.from_pretrained(
    VLM_ID,
    torch_dtype = torch.bfloat16,
    device_map  = "auto",
)
vlm_model.eval()

used  = torch.cuda.memory_allocated(0) / 1e9
total = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"VLM loaded successfully")
print(f"VRAM used : {used:.1f} GB  /  {total:.0f} GB total")
print(f"VRAM free : {total - used:.1f} GB remaining")

from transformers import AutoModelForCausalLM, AutoTokenizer

LLM_ID = "Qwen/Qwen2.5-7B-Instruct"
print(f"Loading {LLM_ID}...")

llm_tokenizer = AutoTokenizer.from_pretrained(LLM_ID)

llm_model = AutoModelForCausalLM.from_pretrained(
    LLM_ID,
    torch_dtype = torch.bfloat16,
    device_map  = "auto",
)
llm_model.eval()

used  = torch.cuda.memory_allocated(0) / 1e9
total = torch.cuda.get_device_properties(0).total_memory / 1e9
free  = total - used
print(f"Both models loaded")
print(f"VRAM used : {used:.1f} GB  /  {total:.0f} GB total")
print(f"VRAM free : {free:.1f} GB remaining")

if free < 4:
    print("WARNING: less than 4GB free — inference may run out of memory")
    print("Fix: add load_in_4bit=True to the LLM from_pretrained call")
else:
    print("Memory headroom is healthy — ready for inference")

from PIL import Image
import numpy as np

SAMPLE_EVERY_N_SECONDS = 10

def extract_frames(video_path, every_n_sec=5):
    cap      = cv2.VideoCapture(video_path)
    fps_val  = cap.get(cv2.CAP_PROP_FPS)
    interval = max(1, int(fps_val * every_n_sec))
    frames   = []
    idx      = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if idx % interval == 0:
            h, w = frame.shape[:2]
            if w > 1280:
                scale = 1280 / w
                frame = cv2.resize(frame,
                    (1280, int(h * scale)),
                    interpolation=cv2.INTER_AREA)
            pil_img   = Image.fromarray(
                cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            timestamp = idx / fps_val
            frames.append({
                "timestamp"  : timestamp,
                "time_label" : f"{int(timestamp//60):02d}:{int(timestamp%60):02d}",
                "image"      : pil_img
            })
        idx += 1

    cap.release()
    return frames

frames = extract_frames(VIDEO_PATH, SAMPLE_EVERY_N_SECONDS)
print(f"Extracted {len(frames)} frames")
print(f"Span : {frames[0]['time_label']} to {frames[-1]['time_label']}")
frames[0]['image']

import json
from tqdm import tqdm

VLM_PROMPT = """Analyze this video frame carefully.
Return ONLY valid JSON — no markdown, no extra text:
{
  "scene": "one sentence describing the overall scene",
  "people": "number visible and what they are doing",
  "objects": ["main", "objects", "present"],
  "activity": "the main activity happening",
  "anomaly": "any safety issue or unusual event, or null"
}"""

def analyze_frame(pil_image):
    messages = [{
        "role": "user",
        "content": [
            {"type": "image", "image": pil_image},
            {"type": "text",  "text": VLM_PROMPT}
        ]
    }]
    text = vlm_processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = vlm_processor(
        text=[ text ],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt"
    ).to("cuda")

    with torch.no_grad():
        output_ids = vlm_model.generate(
            **inputs,
            max_new_tokens = 200,
            do_sample      = False,
        )

    new_tokens = output_ids[0][len(inputs.input_ids[0]):]
    raw = vlm_processor.decode(new_tokens, skip_special_tokens=True).strip()

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        clean = raw.split("```json")[-1].split("```")[0].strip()
        try:
            return json.loads(clean)
        except:
            return {"scene": raw, "people": "", "objects": [],
                    "activity": "", "anomaly": None}

results = []
for f in tqdm(frames, desc="Analyzing frames"):
    try:
        analysis = analyze_frame(f["image"])
        results.append({"timestamp": round(f["timestamp"],1),
                        "time_label": f["time_label"], **analysis})
    except Exception as e:
        print(f"\nError at {f['time_label']}: {e}")
        results.append({"timestamp": round(f["timestamp"],1),
                        "time_label": f["time_label"],
                        "scene": "error", "error": str(e)})

print(f"\nDone — {len(results)} frames analyzed")
for r in results[:3]:
    print(f"[{r['time_label']}] {r.get('scene','')}")

def build_timeline(results):
    lines = []
    for r in results:
        flag = " [ANOMALY]" if r.get("anomaly") else ""
        line = (f"[{r['time_label']}]{flag}  "
                f"{r.get('scene','')}  |  "
                f"Activity: {r.get('activity','')}")
        lines.append(line)
    return "\n".join(lines)

def query_video(question, results):
    timeline = build_timeline(results)
    messages = [
        {"role": "system", "content": (
            "You are a precise video analyst. "
            "Answer questions using only the timestamped data. "
            "Always cite specific timestamps."
        )},
        {"role": "user", "content": (
            f"Video timeline ({len(results)} frames, "
            f"sampled every {SAMPLE_EVERY_N_SECONDS}s):\n\n"
            f"{timeline}\n\n"
            f"Question: {question}"
        )}
    ]
    text = llm_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = llm_tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad():
        output = llm_model.generate(
            **inputs,
            max_new_tokens = 400,
            do_sample      = False,
        )

    new_tokens = output[0][inputs.input_ids.shape[1]:]
    return llm_tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

questions = [
    "Summarize what happens in this video overall.",
    "Were there any anomalies or safety issues? List timestamps.",
    "What objects appear most frequently in the footage?",
]
for q in questions:
    print(f"Q: {q}")
    print(f"A: {query_video(q, results)}")
    print("-" * 60)

import json
from google.colab import files

save_data = [
    {k: v for k, v in r.items() if k != "image"}
    for r in results
]

OUTPUT = "video_analysis.json"
with open(OUTPUT, "w") as f:
    json.dump(save_data, f, indent=2)
print(f"Saved {len(save_data)} frame results to {OUTPUT}")

files.download(OUTPUT)

anomalies = [
    r for r in save_data
    if r.get("anomaly") and r["anomaly"] not in (None, "null", "")
]
total = len(save_data)
print(f"\nSummary")
print(f"  Frames analyzed : {total}")
print(f"  Anomalies found : {len(anomalies)}")
for a in anomalies:
    print(f"  [{a['time_label']}] {a['anomaly']}")